#1
stringone = 'CACACTAATTCGCCAGGGATCCACACTTCGAGGTGAACGTAAGGGAGGATATCCATTCGCCGGCACAGAACTTAGTATAACCCGGTGTCGATTGCTCGATATCCCGCTACACTTCTTTATATCGTACCGCTAGTCGAGTATTGACGCGGTGCAAGCTCACACCTTCTCGATATCTGGTGTCGGTTGTGAATGACGCTGCATATCGGTACCACGGCATTTACCAGGAGGATTCCTTCCAGGTGTCCTGACCTCGAGGCGGGGTTGCCTTTGCTGCACGTCTATGCTACGATTTAAAACTGCTTCCATGGGGAAGGCGTGAATAGACCCGCAACCTACTTATACCGTGAAGTCAGGAGTCGCATTGTAGTCCGAGTATGCGGTTTCTCAAGCCATCCTCTTCGACGCTCTACGCTGATGCGGCTGCCATAAATACGGCTCGTAGAATTGTTTCAACGGCTCCATCCGGCTTCATATCGTGCGCTCTGGGAGTGATATACAGGGTGCGAAGAACCGAGTACGCAAGTCAGCCCTCTCACATGGGGGTTAACAGTATCACTCGCTTTTGCCCCGAGTCTACTACCCATACGTCCTAGATTTGATGACTAGGAGGGAAAATGTATCTTCCCAGGTAATCTATTATTATCCGCATCCTAGCGCGAAGGCTCCTTAAGTGACGGGTCCGAAGGTGATGCACCATACTTGCTGATAGATAATCACTACTTACTCACGTAACGCAGTGCCGCACTGCCAGTTGACAGTCTACACTCGCTACTCTTGAAGGGAGAGGCCTGTAATGACTTTCAACCATTTCCGGATCCGCAATCGACGACAATCCTCTCCCGTGGGGGGCTGCCCGTGTCGATCGACTGCTCTCGCGCTATCAGCTCATACATGTA'
a = 0
c = 0
g = 0
t = 0

for i in stringone:
    if i == 'A':
        a +=1
    elif i == 'C':
        c +=1
    elif i == 'G':
        g +=1
    elif i == 'T':
        t +=1

#2
f = 'CTCACGGCAGGCTACGCGAACCGGCACACATAAGTACACCACTTTGATTGAGAAGCATTTCCCGTTAGCTGGCTTCCACCGGATTCTCAGGAAAGACATGCCTTATATATCGACACGATGGCTGTCTGGAAGATGAGACTAAAGGCCTAGACTTGATCAAGTCGTGCAGACCACCATTGCATTAACATCCTATTTTTAATGAAACGTAGTCTGGGCCGTACCGGAGCTGGGGAAACACTATGCGGGAGCGGTCTACGACTGGATGCTAAGACCGCCCCGATCAGGCTTCATAGCAGCGTGGACGCAATGCTATGATTGATGATCGGCATAAAAGTTTCCGCGAAACGAAGGCTTCCTTTCTGTCTTTAATTCAGTGATGTCCGACGTTATCAGGGTGTCACATTGGATCGATCGAAAAAAGAGAGAACCGGTAGTGTCTACGGGCCGGGCTTTTCGGCGGCACCTCGCTGCGACGGTTGGACAGCCGCGATGAACCTGTACTCCCCACGTCTCCATCGCTTTAAGCCCCCGCGACAGCTGTCGGCCGCCTCGCAGTGTGATGGTAATACGACGACGACTAGGTGTTCCAATTACCACCGCACGTTATTCCTTAGGCAGTTTGGACCATATCTTAGTTCATACTCGCCCCAGAGACCACTTCGTTTTGATAAGGACGTCGCCCTTCCCGCACGTATTTCTAGTTTCACTGCGGCCACGGGCTATACCGAGCCCTCATAATCGCTTTGCCACCACACACCTTCCCGTTTTGAAGCATTTCTCTTTTTCTTGGCGGGGTTTGTAGTGGAGAAGGACCATCTTAAAGTCAATGAGAGCAATAGTAAGTGGGCGTCTTGAGTACAAACCTATCTTCCGATACCAGACTTCGGAGCCTTCGGACTGGCTTGAACTTGGTGTCTAGCCAGAGTGGGCGATGATGGGCATTCACACCGATGGAACATTACCCTGTTTCA'
g = f.replace('T', 'U')

#3
dna = 'AGAGGCGTGTGTTTTCCGCGCTTGCATTCTCCAACGCTCGACTAGCAATCGCAGCGAATCGATGGAAACGTTCTACTCGGGGCGTATGCCGCCTACATCCAGACGAAGCAACACTGCTTTTGGTTGGCACCAAGTTTCTGTTATTATACTCTTCCTGAACACCCCACGGTCTTCACGCGGATGCGAACCGAAGCCCTTCTCTCAGTTAAGGTGGCCATATGCTGTGCGGAAGACGGAGAAAAGGTCGCAAAGCAATTGATCTACTCGACCCCATTGGAACCATTATAAACGCAGCAAAGGTCTCCACGCAGGAGGGTTTATAGACGGCTCAGCGGCGATCTACACGGTGGTAAGACAAACATACCATTATACAAAGATTGACGAGGTTCTAGGCAGCCCTCGTTCCTATTCCCCAAGCAGGTCAATTTCCTCAGGCGGCTTATATTGCTGACTTCCTTTGGGATTGCCGGTCCGGGGCAGGCTTTGAGGACGATAAAGGCAACGCGCGCGTCACTAAGTGCATTCGTACATGTGAAAATTCCTGGCGTGTTTACGTTCATCTTCTTCTGATAGCACGGTTGCGTTCCCTTCCCAGTTTTAGCTTTCGAAGCATACTCACGGCAAAGCTAGCCCGACTCAAGCGTATCCCGTGGCGCGCAGGAGTCATGCGCACCTGTTAGTCACAGTAGTAGCCCTACTCAGAGGCTAGCAACGAGATGTAGTTATTGTGCAAGTGTTTCTTCCCACTACAACTGCCTTCATGCAGCATAGTGATACATCAAGTAGCTATAACATCGATTGAACCCCTACTACTCACATGAATCTTCAATTTC'
rna = ''

for i in reversed(dna):
    if i == 'A':
        rna += 'T'
    elif i == 'C':
        rna += 'G'
    elif i == 'G':
        rna += 'C'
    elif i == 'T':
        rna += 'A'

#4 Fibbonacci Rabbits
n = 0
k = 0
num = 0
def fib(n, k):
    if n <= 2:
        return 1
    elif n ==3:
        return 1+k
    else:
        return num + (fib(n-2, k)*k) + fib(n-1, k)

# 5 Mortal Fibbonacci Rabbits - incorrect
n = 0
m = 0
x = 0
num = 0
def mortal_rabs(n, m):
    global x
    x += 1
    print(round(x,0))
    if n < 0:
        return 0
    elif n <= 2:
        return 1
    else: 
        return num + mortal_rabs(n-2, m)+mortal_rabs(n-1, m)-mortal_rabs(n-(m+1), m)

#5 Mortal Fibbonnacci Rabbits v2 (kinda maybe sorta got this from chatgpt)
def dyingrabs(n, m):
    global x
    x=0
    if n <= 2:
        return 1
    
    dp = [1] * (n+1)
    dp[1] = 1
    dp[2] = 1

    for i in range(3, n+1):
        if i <=m:
            x+=2
            dp[i] = dp[i-1]+dp[i-2]
        else:
            x+=3
            dp[i] = dp[i-1]+dp[i-2]-dp[i-m-1]
    
    return dp[n]
print(dyingrabs(86, 16))
print('Loops: ', x)